name: few-shot-learning-reproduction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - pyyaml>=6.0
  - pip
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - tqdm>=4.65.0
    - wandb>=0.15.0
    - click>=8.0.0
    - python-dotenv>=1.0.0
    - plotly>=5.15.0
    - black>=23.0.0
    - isort>=5.12.0
    - pytest>=7.0.0
