analysis:
  confidence_analysis: true
  error_analysis: true
  length_analysis: true
metrics:
- accuracy
- f1_macro
- f1_per_class
- confusion_matrix
output:
  figures_dir: results/figures
  metrics_dir: results/metrics
visualization:
  create_plots: true
  plot_dpi: 300
  plot_format: png
