data:
  max_length: 800
  test_size: 350
  val_size: 100
few_shot:
  max_eval: 100
  shots:
  - 0
  - 1
  - 2
  - 5
  - 10
model:
  max_new_tokens: 10
  name: gpt2
  temperature: 0.1
project_name: few-shot-learning-reproduction
